### ISSUE TITLE
:star2: Feature request: Extend database of single-crystal and whole rock/aggregate elastic constants

### ISSUE THREAD

**Issue by hemmelig** [hemmelig/AnisotroPy#1]
---
# Feature request
### Summary:
  Extend database of single-crystal and whole rock/aggregate elastic constants, improve core materials code, and consolidate with Telewavesim

---

**Is your feature request related to a problem? Please describe.**
No - simply an extension.

**Describe the solution you'd like**
Extend the existing database to include (at least!) all those materials that are currently available in the `elast.py` module of the Telewavesim package. In tandem, build in some additional functionality to the `anisotropy.materials.Material` class itself. For example, calculating the Voigt/Reuss/Voigt-Reuss-Hill aggregate bulk/shear moduli (equations set out in Hill, 1952).

At this stage, it is worth considering what should be required for the elastic constants for a given material to be included. At a minimum, this should probably be two additional fields on the `anisotropy.materials.Material` class - one containing a material identifier, likely just a string, and the other containing a reference. This could either be the full reference string (probably best) or simply the DOI.

Comprehensive tests should also be written that explore the functions in `anisotropy.materials.core.py` and some simple tutorial examples could be written that describe how to load a material from the database, how to mix an aggregate material, how to water the single-crystal elastic constants down with their isotropic component, how to define a custom material that is not in the database (and maybe some instructions on how to contribute it).

To-do list
------------
- [x] Expand elastic database to include all those minerals that are available in Telewavesim - 4bcf0f3
  - [x] Implement generalised methods to calculate the bulk/shear moduli (in the cases of both isotropic and generally anisotropic elastic tensors) - 32f4354
  - [x] Add `material_id` and `material_reference` attributes to `Material` class - 57d1fdf
- [x] Write a function to calculate the isotropic component of a general elastic stiffness tensor (Browaeys and Chevrot, 2004) - 98fe159
- [ ] Write tests
  - [x] Elastic constant averaging functions
  - [x] Bulk/shear moduli functions
  - [ ] Calculate polarisation - this one I definitely need to spend a little time understanding. Sketch vector diagram once solved.
  - [x] Extensive test for the conversion between Voigt/full 4th rank tensor form - test all 81 elements of the tensor!
- [x] Create tutorials - 839e959
  - [x] Loading a material
  - [x] Mixing an aggregate
  - [x] Watering down single-crystal tensors with their isotropic component
  - [x] Defining custom materials (not in the database)

Something to do in a separate PR would be to test this module in-situ in the Telewavesim package, to ensure that all requirements are met there and this module can then become the single source for elastic tensor representation.

**Comment by wasjabloch** [comment]
I'm about to add to my fork of the _test_materials_module_ branch the "olivine aggregates" of:

Ismaı̈l, W.B. & Mainprice, D., 1998. An olivine fabric database: an overview of upper mantle fabrics and seismic anisotropy, Tectonophysics, 296 (1–2)/ https://doi.org/10.1016/S0040-1951(98)00141-3.

and tempt to name them:

`"peridotite_fastridge"`, `"peridotie_subduction"` and `"peridotite_kimberlite"`.

Any objections?
