### ISSUE TITLE
Material.rotate() should rotate self.C or return Material, instead of returning C

### ISSUE THREAD

**Issue by wasjabloch** [hemmelig/AnisotroPy#4]
Currently, `Material.rotate(alpha, beta, gamma, **kwargs) ` returns a numpy array of the rotated tensor. In my opinion, it would be more intuitive if it would either:

a) return nothing, but write the rotated tensor straight to `self.C`, or
b) return a copy of Material with the rotated tensor

imho (a) is more intuitive, but there may be reasons to prefer (b).

I'm happy to implement either.

**Comment by hemmelig** [comment]
Yes, that would be sensible. Option A would require a user to explicitly make copies of the object if they were using one material as a base for an aggregate - easy path to errors. Could offer both via an `inplace` keyword argument? Something like:

```
    def rotate(self, alpha, beta, gamma, order=[1, 2, 3], mode="extrinsic", inplace=False):
        """Helper function to perform an arbitrary 3-D rotation of C."""
        R = self._rotate_3d(alpha, beta, gamma, order, mode)
        Q = self._build_bond_matrix(R)

        rotated_C = np.dot(Q, np.dot(self.C, Q.T))
        if inplace:
            self.C = rotated_C
        else:
            return Material(rotated_C, self.rho, self.material_id, self.reference)
```

Makes the return type weird, but it's common in packages like pandas.
